### ISSUE TITLE
Turning LoraStackLoader switch to off has no effect

### ISSUE THREAD

**Issue by ryancom16** [picturesonpictures/comfy_PoP#1]
Problem:
I'm using the LoraStackLoader10_PoP, I have a lora loaded for 1 and 2. 1 is enabled and 2 is off. The lora is still loaded unless I select none for the lora name.

**Comment by ryancom16** [comment]
Is it because switch can have possible values "off" and "on" https://github.com/picturesonpictures/comfy_PoP/blob/main/LoraStackLoader10_PoP.py#L17

but is being evaluated against "None" ?\
https://github.com/picturesonpictures/comfy_PoP/blob/main/LoraStackLoader10_PoP.py#L57

**Comment by ryancom16** [comment]
Confirmed working if you change the following 
`if switch == 'None' or lora_name is None:`
to
`if switch == 'Off' or lora_name is None:`

Will need to be updated here as well.
https://github.com/picturesonpictures/comfy_PoP/blob/main/LoraStackLoader_PoP.py#L45

**Comment by picturesonpictures** [comment]
Thanks, 

> Confirmed working if you change the following `if switch == 'None' or lora_name is None:` to `if switch == 'Off' or lora_name is None:`
> 
> Will need to be updated here as well. https://github.com/picturesonpictures/comfy_PoP/blob/main/LoraStackLoader_PoP.py#L45

Thanks! Doing my best with these things. I'll have it fixed momentarily. Please let me know if you have any other issues that you believe need attention.

**Comment by picturesonpictures** [comment]
Alright, the on/off switches should be good to go now. I tested them out and they're doing what should now.  Again, I really appreciate you taking the time to let me know. if you ever have any other issues, ideas, etc, please don't hesitate to let me know.
